var CAREERS = [
    "Administrator",
     "Lawyer",
     "Aeronaut",
     "Archivist-Archivist Archive",
     "Artist/Technician in amusement shows",
     "Social Worker",
     "Professional Football Athlete",
     "Librarian'",
     "Biomedical", 
     "Biologist",
     "Civil Fireman",
     "Commercial",
     "Accountant", 
     "Realtor",
     "Insurance Broker",
     "Customs Broker",
     "Agronomist Engineer",
     "Domestic Economist",
     "Economist",
     "Physical Educator",
     "Domestic Employee", 
     "Nursing",
     "Sickening",
     "Security Engineering",
     "Physiotherapist and Occupational Therapist",
     "Pharmacist", 
     "Speech therapist",
     "Prospector",
     "Geographer", 
     "Geologist",
     "Car Keeper and Washer",
     "Traffic Instructor",
     "Journalist",
     "Auctioneer",
     "Rural Auctioneer",
     "Masseuse",
     "Doctor",
     "Museologist",
     "Nutritionist",
     "Oceanographer",
     "Dentistry",
     "Educational Advisor",
     "Professional Fisherman",
     "Psychology",
     "Advertising-Advertising Agent",
     "Chemist",
     "Radio host",
     "Autonomous Commercial Representatives",
     "Repentista",
     "Sociologist",
     "Sommelier",
     "Taxi driver",
     "Translator and Interpreter of the Brazilian Sign Language - LIBRAS",
     "Technical Administration",
     "Industrial Technician", 
     "Dental Prosthesis Technician",
    "Radiology Technician", 
    "Turismologist",
    "Zootechnicist"
];

let getCareers = () => {
    return CAREERS;
};

export default {getCareers};